### ISSUE TITLE
Untie id and class

### ISSUE THREAD

**Issue by Shadowblitz16** [Wohlstand/TheXTech#692] opened 2024-01-18 15:25 UTC
What if entity behavior was tied to a dynamic enum type instead of their id?

Then we could say take npc-x and change it's type to be npc-y and then npc-x then acts exactly like npc-y

**Comment by Wohlstand** [comment] 2024-01-18 15:34
Here is a plan for the future to turn entire spahgetti code into array of function pointers, and that will allow assigning of different algorithms to any ID.

**Comment by ds-sloth** [comment] 2024-01-18 15:41
This is a good suggestion, also see #282 for more notes on the idea.

**Comment by ds-sloth** [comment] 2024-02-16 19:07
Closing as an approximate duplicate of #282, and as a portion of #472.

**Closed by ds-sloth** 2024-02-16 19:07 UTC
