### ISSUE TITLE
Water Splash Effect Occurs Incorrectly with Fire Flower

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Wohlstand/TheXTech#16] opened 2020-05-16 02:23 UTC
When using a Fire Flower under water to create Fire Balls, a splash effect plays at the surface of the water with a position corresponding to the Fire Ball's initial position.

![tmp](https://user-images.githubusercontent.com/30162808/82108160-74d2c700-96e1-11ea-8e2b-63130e27f155.gif)

**Comment by Wohlstand** [comment] 2020-05-27 20:23
Interesting... Going to verify this at both vanilla SMBX and XTech for just in a case...

**Comment by Wohlstand** [comment] 2020-05-27 20:32
Yeh, I understand the nature of this thing: the effect happen in only a condition player touches this BGO, and its height is big:
![Scr_2020-05-27_23-28-49](https://user-images.githubusercontent.com/6751442/83069054-f3305100-a071-11ea-9fad-34ee071424b1.gif)
by a fun fact: the splash effect happens even when BGO itself is underwater depth!
I think, to avoid this glitch I need to check at least, the spawn of the fireball should cause a splash in a specific height limit to don't play this splash oddly.

**Comment by Wohlstand** [comment] 2020-05-27 20:35
This glitch is reproduced in Vanilla SMBX, XTech, and SMBX2. In SMBX38A the effect happens in the only condition the BGO is properly aligned to the top of the water surface rectangle while in SMBX 1.3 and XTech it happens while just touching the water-top BGO.

**Comment by Wohlstand** [comment] 2020-05-27 20:38
It's how in SMBX-38A this works:
![Peek 2020-05-27 23-37](https://user-images.githubusercontent.com/6751442/83069736-16a7cb80-a073-11ea-9988-4dfd24921241.gif)
Probably I should make something similar like this...

**Comment by ChristianSilvermoon** [comment] 2020-05-28 12:02
The more you know. Huh!
Underwater splashes, now that's kinda funny x3

**Comment by Wohlstand** [comment] 2021-04-19 08:41
Okay, just now I made the fix for this mess:
![Scr_2021-04-19_11-25-51](https://user-images.githubusercontent.com/6751442/115207258-18073a00-a104-11eb-890a-3e088318c4d3.gif)

Should work now properly, please check the dev build or pull the latest sources! :fox_face: :+1:

**Comment by Wohlstand** [comment] 2021-04-25 21:22
Closing due to no reply.

**Closed by Wohlstand** 2021-04-25 21:22 UTC
Labels: NEED A TEST, vanilla bug

**Comment by ChristianSilvermoon** [comment] 2021-04-26 14:42
Confirmed! Sorry for the late reply and test!
