### ISSUE TITLE
[BUG] Inaccuracy/Crash at negative size block handling

### ISSUE THREAD

**Issue by M0REKZ** [Wohlstand/TheXTech#655] opened 2023-12-05 13:49 UTC
**Describe the issue**

I got this bug because i wonder if i could flip blocks like in another game instead of using multiple blocks (of course couldn't).

When loading a level with blocks at -16 size, TheXTech will render it anyways, while vanilla only would render the animated one, and at -64 size TheXTech _actually crashes_ while vanilla will just run normally.

**Example Case**

The levels where i was testing, you must play **double-negative-size.lvl** for the crash, and **half-negative-size.lvl** for the inaccurate rendering.

[Negative-Test.zip](https://github.com/Wohlstand/TheXTech/files/13560571/Negative-Test.zip)

**Screenshots**

XTech:
half-negative-size.lvl
<img width="1438" alt="half-xtech" src="https://github.com/Wohlstand/TheXTech/assets/60852359/747bab7c-27f8-449b-a185-0d6da79cfc64">

double-negative-size.lvl
<img width="1133" alt="double-xtech" src="https://github.com/Wohlstand/TheXTech/assets/60852359/0f5f22eb-73c0-4d9c-a508-d45505473c61">

Vanilla 1.3.0.1:
half-negative-size.lvl
<img width="823" alt="half-vanilla" src="https://github.com/Wohlstand/TheXTech/assets/60852359/5c6abae3-6418-4d6b-aa81-0a54364d237b">

double-negative-size.lvl
<img width="824" alt="double-vanilla" src="https://github.com/Wohlstand/TheXTech/assets/60852359/b0c16063-2f4a-4e56-9a92-ee2cf1e59fdf">

**Additional context**

* TheXTech Version: 1.3.6.2

* Vanilla was tested on a Windows 11 ARM64 Virtual Machine

* Only tested with blocks that normally are 32x32

* Only tested sizes in the example case levels

* I don't know about others game objects that could have inaccuracies with negative sizes.

LOG:
[TheXTech_log_2023_12_05_10_35_33.txt](https://github.com/Wohlstand/TheXTech/files/13560890/TheXTech_log_2023_12_05_10_35_33.txt)

**Comment by Wohlstand** [comment] 2023-12-05 14:30
Looks like a bug in the indexing code 🤔

**Comment by ds-sloth** [comment] 2023-12-06 00:59
Since the vanilla behavior is difficult to reproduce here and no vanilla content makes use of this hack, we have decided to refuse to load blocks with negative dimensions. The current main branch code should no longer crash (or render the blocks). Can you check that that is the case?

Before we close this issue: should we silently ignore the improper blocks, or should we treat this as an error and refuse to load the level at all?

**Comment by M0REKZ** [comment] 2023-12-06 11:54
Now the level wont crash the game and the blocks wont be rendered, also the blocks now have the same behaviour in all negative level files.

<img width="1078" alt="1" src="https://github.com/Wohlstand/TheXTech/assets/60852359/e9302f80-e127-4044-9a7e-9079abb15824">
<img width="1010" alt="2" src="https://github.com/Wohlstand/TheXTech/assets/60852359/1e314e29-5da4-4964-b191-ba2eeccb6f86">

**Comment by ds-sloth** [comment] 2023-12-07 00:19
Great. @Wohlstand, are we good to close now?

**Closed** 2023-12-09 19:26 UTC
Labels: bug, NEED A TEST, hack compat
